/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DedalADLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return fr.ema.dedal.xtext.ui.internal.DedalADLActivator.getInstance().getInjector("fr.ema.dedal.xtext.DedalADL");
	}

}
