/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DedalADLUiModule extends fr.ema.dedal.xtext.ui.AbstractDedalADLUiModule {
	public DedalADLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
