/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.ema.dedal.xtext.ui.internal.DedalADLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DedalADLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DedalADLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DedalADLActivator.getInstance().getInjector(DedalADLActivator.FR_EMA_DEDAL_XTEXT_DEDALADL);
	}
	
}
