/*******************************************************************************
 * Copyright (C) 2019 aleborgne
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DedalADLStandaloneSetup extends DedalADLStandaloneSetupGenerated{

	public static void doSetup() {
		new DedalADLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

