/*******************************************************************************
 * Copyright (C) 2019 aleborgne
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DedalADLRuntimeModule extends fr.ema.dedal.xtext.AbstractDedalADLRuntimeModule {

}
