/**
 * generated by Xtext
 */
package fr.ema.dedal.xtext.validation;

import fr.ema.dedal.xtext.validation.AbstractDedalADLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DedalADLValidator extends AbstractDedalADLValidator {
}
