/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DedalADLStandaloneSetup extends DedalADLStandaloneSetupGenerated{

	public static void doSetup() {
		new DedalADLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

