/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DedalADLRuntimeModule extends fr.ema.dedal.xtext.AbstractDedalADLRuntimeModule {

}
