/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DedalADLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/ema/dedal/xtext/parser/antlr/internal/InternalDedalADL.tokens");
	}
}
