/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.ema.dedal.xtext.services.DedalADLGrammarAccess;

public class DedalADLParser extends AbstractContentAssistParser {
	
	@Inject
	private DedalADLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.ema.dedal.xtext.ui.contentassist.antlr.internal.InternalDedalADLParser createParser() {
		fr.ema.dedal.xtext.ui.contentassist.antlr.internal.InternalDedalADLParser result = new fr.ema.dedal.xtext.ui.contentassist.antlr.internal.InternalDedalADLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getArchitectureDescriptionAccess().getAlternatives(), "rule__ArchitectureDescription__Alternatives");
					put(grammarAccess.getComponentAccess().getAlternatives(), "rule__Component__Alternatives");
					put(grammarAccess.getCompClassAccess().getAlternatives(), "rule__CompClass__Alternatives");
					put(grammarAccess.getInteractionAccess().getAlternatives(), "rule__Interaction__Alternatives");
					put(grammarAccess.getPortAccess().getAlternatives(), "rule__Port__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getDelegated_interface_listAccess().getAlternatives(), "rule__Delegated_interface_list__Alternatives");
					put(grammarAccess.getDelegated_interface_listAccess().getAlternatives_1_4(), "rule__Delegated_interface_list__Alternatives_1_4");
					put(grammarAccess.getConstraint_expressionAccess().getAlternatives(), "rule__Constraint_expression__Alternatives");
					put(grammarAccess.getLogical_constraintAccess().getAlternatives(), "rule__Logical_constraint__Alternatives");
					put(grammarAccess.getRelational_constraintAccess().getAlternatives_1(), "rule__Relational_constraint__Alternatives_1");
					put(grammarAccess.getRelational_constraintAccess().getAlternatives_2(), "rule__Relational_constraint__Alternatives_2");
					put(grammarAccess.getChange_timeAccess().getAlternatives(), "rule__Change_time__Alternatives");
					put(grammarAccess.getInitial_levelAccess().getAlternatives(), "rule__Initial_level__Alternatives");
					put(grammarAccess.getChange_operationAccess().getAlternatives(), "rule__Change_operation__Alternatives");
					put(grammarAccess.getArchitecture_elementAccess().getAlternatives(), "rule__Architecture_element__Alternatives");
					put(grammarAccess.getSpecification_elementAccess().getAlternatives(), "rule__Specification_element__Alternatives");
					put(grammarAccess.getConfiguration_elementAccess().getAlternatives(), "rule__Configuration_element__Alternatives");
					put(grammarAccess.getAssembly_elementAccess().getAlternatives(), "rule__Assembly_element__Alternatives");
					put(grammarAccess.getChange_purposeAccess().getAlternatives(), "rule__Change_purpose__Alternatives");
					put(grammarAccess.getChange_originAccess().getAlternatives(), "rule__Change_origin__Alternatives");
					put(grammarAccess.getDIRECTIONAccess().getAlternatives(), "rule__DIRECTION__Alternatives");
					put(grammarAccess.getATTRIBUTE_TYPEAccess().getAlternatives(), "rule__ATTRIBUTE_TYPE__Alternatives");
					put(grammarAccess.getDedalDiagramAccess().getGroup(), "rule__DedalDiagram__Group__0");
					put(grammarAccess.getDedalDiagramAccess().getGroup_2(), "rule__DedalDiagram__Group_2__0");
					put(grammarAccess.getDedalDiagramAccess().getGroup_2_0(), "rule__DedalDiagram__Group_2_0__0");
					put(grammarAccess.getDedalDiagramAccess().getGroup_2_0_3(), "rule__DedalDiagram__Group_2_0_3__0");
					put(grammarAccess.getDedalDiagramAccess().getGroup_2_1(), "rule__DedalDiagram__Group_2_1__0");
					put(grammarAccess.getDedalDiagramAccess().getGroup_2_1_3(), "rule__DedalDiagram__Group_2_1_3__0");
					put(grammarAccess.getRepositoryAccess().getGroup(), "rule__Repository__Group__0");
					put(grammarAccess.getRepositoryAccess().getGroup_2(), "rule__Repository__Group_2__0");
					put(grammarAccess.getRepositoryAccess().getGroup_2_3(), "rule__Repository__Group_2_3__0");
					put(grammarAccess.getRepositoryAccess().getGroup_3(), "rule__Repository__Group_3__0");
					put(grammarAccess.getRepositoryAccess().getGroup_3_3(), "rule__Repository__Group_3_3__0");
					put(grammarAccess.getInterfaceTypeAccess().getGroup(), "rule__InterfaceType__Group__0");
					put(grammarAccess.getInterfaceTypeAccess().getGroup_5(), "rule__InterfaceType__Group_5__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getSignatureAccess().getGroup(), "rule__Signature__Group__0");
					put(grammarAccess.getSignatureAccess().getGroup_2(), "rule__Signature__Group_2__0");
					put(grammarAccess.getSignatureAccess().getGroup_3(), "rule__Signature__Group_3__0");
					put(grammarAccess.getSignatureAccess().getGroup_4(), "rule__Signature__Group_4__0");
					put(grammarAccess.getSignatureAccess().getGroup_4_3(), "rule__Signature__Group_4_3__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_2(), "rule__Parameter__Group_2__0");
					put(grammarAccess.getParameterAccess().getGroup_3(), "rule__Parameter__Group_3__0");
					put(grammarAccess.getSpecificationAccess().getGroup(), "rule__Specification__Group__0");
					put(grammarAccess.getSpecificationAccess().getGroup_2(), "rule__Specification__Group_2__0");
					put(grammarAccess.getSpecificationAccess().getGroup_2_2(), "rule__Specification__Group_2_2__0");
					put(grammarAccess.getSpecificationAccess().getGroup_3(), "rule__Specification__Group_3__0");
					put(grammarAccess.getSpecificationAccess().getGroup_4(), "rule__Specification__Group_4__0");
					put(grammarAccess.getSpecificationAccess().getGroup_5(), "rule__Specification__Group_5__0");
					put(grammarAccess.getSpecificationAccess().getGroup_6(), "rule__Specification__Group_6__0");
					put(grammarAccess.getSpecificationAccess().getGroup_7(), "rule__Specification__Group_7__0");
					put(grammarAccess.getSpecificationAccess().getGroup_7_2(), "rule__Specification__Group_7_2__0");
					put(grammarAccess.getCompRoleAccess().getGroup(), "rule__CompRole__Group__0");
					put(grammarAccess.getCompRoleAccess().getGroup_4(), "rule__CompRole__Group_4__0");
					put(grammarAccess.getCompRoleAccess().getGroup_4_2(), "rule__CompRole__Group_4_2__0");
					put(grammarAccess.getCompRoleAccess().getGroup_5(), "rule__CompRole__Group_5__0");
					put(grammarAccess.getCompRoleAccess().getGroup_5_2(), "rule__CompRole__Group_5_2__0");
					put(grammarAccess.getCompRoleAccess().getGroup_6(), "rule__CompRole__Group_6__0");
					put(grammarAccess.getCompRoleAccess().getGroup_7(), "rule__CompRole__Group_7__0");
					put(grammarAccess.getCompRoleAccess().getGroup_8(), "rule__CompRole__Group_8__0");
					put(grammarAccess.getCompRoleAccess().getGroup_8_2(), "rule__CompRole__Group_8_2__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup_6(), "rule__Interface__Group_6__0");
					put(grammarAccess.getInterfaceAccess().getGroup_7(), "rule__Interface__Group_7__0");
					put(grammarAccess.getRoleConnectionAccess().getGroup(), "rule__RoleConnection__Group__0");
					put(grammarAccess.getConfigurationAccess().getGroup(), "rule__Configuration__Group__0");
					put(grammarAccess.getConfigurationAccess().getGroup_2(), "rule__Configuration__Group_2__0");
					put(grammarAccess.getConfigurationAccess().getGroup_2_2(), "rule__Configuration__Group_2_2__0");
					put(grammarAccess.getConfigurationAccess().getGroup_2_3(), "rule__Configuration__Group_2_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup_3(), "rule__Configuration__Group_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup_4(), "rule__Configuration__Group_4__0");
					put(grammarAccess.getConfigurationAccess().getGroup_5(), "rule__Configuration__Group_5__0");
					put(grammarAccess.getConfigurationAccess().getGroup_6(), "rule__Configuration__Group_6__0");
					put(grammarAccess.getConfigurationAccess().getGroup_6_2(), "rule__Configuration__Group_6_2__0");
					put(grammarAccess.getConfigurationAccess().getGroup_7(), "rule__Configuration__Group_7__0");
					put(grammarAccess.getConfigurationAccess().getGroup_7_4(), "rule__Configuration__Group_7_4__0");
					put(grammarAccess.getConfigurationAccess().getGroup_8(), "rule__Configuration__Group_8__0");
					put(grammarAccess.getConfigurationAccess().getGroup_8_3(), "rule__Configuration__Group_8_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup_9(), "rule__Configuration__Group_9__0");
					put(grammarAccess.getConfigurationAccess().getGroup_9_3(), "rule__Configuration__Group_9_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup_10(), "rule__Configuration__Group_10__0");
					put(grammarAccess.getConfigurationAccess().getGroup_10_3(), "rule__Configuration__Group_10_3__0");
					put(grammarAccess.getCompTypeAccess().getGroup(), "rule__CompType__Group__0");
					put(grammarAccess.getCompTypeAccess().getGroup_4(), "rule__CompType__Group_4__0");
					put(grammarAccess.getCompTypeAccess().getGroup_4_2(), "rule__CompType__Group_4_2__0");
					put(grammarAccess.getCompTypeAccess().getGroup_5(), "rule__CompType__Group_5__0");
					put(grammarAccess.getCompTypeAccess().getGroup_5_2(), "rule__CompType__Group_5_2__0");
					put(grammarAccess.getCompTypeAccess().getGroup_6(), "rule__CompType__Group_6__0");
					put(grammarAccess.getCompTypeAccess().getGroup_6_2(), "rule__CompType__Group_6_2__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup(), "rule__CompClass_Impl__Group__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_2(), "rule__CompClass_Impl__Group_2__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_2_2(), "rule__CompClass_Impl__Group_2_2__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_7(), "rule__CompClass_Impl__Group_7__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_8(), "rule__CompClass_Impl__Group_8__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_8_3(), "rule__CompClass_Impl__Group_8_3__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_9(), "rule__CompClass_Impl__Group_9__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_10(), "rule__CompClass_Impl__Group_10__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_11(), "rule__CompClass_Impl__Group_11__0");
					put(grammarAccess.getCompClass_ImplAccess().getGroup_11_2(), "rule__CompClass_Impl__Group_11_2__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup(), "rule__CompositeCompClass__Group__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_6(), "rule__CompositeCompClass__Group_6__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_6_2(), "rule__CompositeCompClass__Group_6_2__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_7(), "rule__CompositeCompClass__Group_7__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_8(), "rule__CompositeCompClass__Group_8__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_8_3(), "rule__CompositeCompClass__Group_8_3__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_9(), "rule__CompositeCompClass__Group_9__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_10(), "rule__CompositeCompClass__Group_10__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_11(), "rule__CompositeCompClass__Group_11__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_11_3(), "rule__CompositeCompClass__Group_11_3__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_12(), "rule__CompositeCompClass__Group_12__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_12_2(), "rule__CompositeCompClass__Group_12_2__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_13(), "rule__CompositeCompClass__Group_13__0");
					put(grammarAccess.getCompositeCompClassAccess().getGroup_13_2(), "rule__CompositeCompClass__Group_13_2__0");
					put(grammarAccess.getDelegated_interface_listAccess().getGroup_1(), "rule__Delegated_interface_list__Group_1__0");
					put(grammarAccess.getDelegated_interface_listAccess().getGroup_1_4_0(), "rule__Delegated_interface_list__Group_1_4_0__0");
					put(grammarAccess.getDelegated_interface_listAccess().getGroup_1_4_1(), "rule__Delegated_interface_list__Group_1_4_1__0");
					put(grammarAccess.getInner_interfaceAccess().getGroup(), "rule__Inner_interface__Group__0");
					put(grammarAccess.getOuter_interfaceAccess().getGroup(), "rule__Outer_interface__Group__0");
					put(grammarAccess.getComponent_class_identifierAccess().getGroup(), "rule__Component_class_identifier__Group__0");
					put(grammarAccess.getComponent_class_identifierAccess().getGroup_1(), "rule__Component_class_identifier__Group_1__0");
					put(grammarAccess.getConnector_typeAccess().getGroup(), "rule__Connector_type__Group__0");
					put(grammarAccess.getConnector_typeAccess().getGroup_4(), "rule__Connector_type__Group_4__0");
					put(grammarAccess.getConnector_typeAccess().getGroup_7(), "rule__Connector_type__Group_7__0");
					put(grammarAccess.getConnector_classAccess().getGroup(), "rule__Connector_class__Group__0");
					put(grammarAccess.getClassConnectionAccess().getGroup(), "rule__ClassConnection__Group__0");
					put(grammarAccess.getPort_ImplAccess().getGroup(), "rule__Port_Impl__Group__0");
					put(grammarAccess.getPort_ImplAccess().getGroup_5(), "rule__Port_Impl__Group_5__0");
					put(grammarAccess.getCompositePortAccess().getGroup(), "rule__CompositePort__Group__0");
					put(grammarAccess.getCompositePortAccess().getGroup_5(), "rule__CompositePort__Group_5__0");
					put(grammarAccess.getAssemblyAccess().getGroup(), "rule__Assembly__Group__0");
					put(grammarAccess.getAssemblyAccess().getGroup_4(), "rule__Assembly__Group_4__0");
					put(grammarAccess.getAssemblyAccess().getGroup_5(), "rule__Assembly__Group_5__0");
					put(grammarAccess.getAssemblyAccess().getGroup_9(), "rule__Assembly__Group_9__0");
					put(grammarAccess.getAssemblyAccess().getGroup_11(), "rule__Assembly__Group_11__0");
					put(grammarAccess.getAssemblyAccess().getGroup_11_3(), "rule__Assembly__Group_11_3__0");
					put(grammarAccess.getAssemblyAccess().getGroup_12(), "rule__Assembly__Group_12__0");
					put(grammarAccess.getAssemblyAccess().getGroup_13(), "rule__Assembly__Group_13__0");
					put(grammarAccess.getAssemblyAccess().getGroup_14(), "rule__Assembly__Group_14__0");
					put(grammarAccess.getAssemblyAccess().getGroup_14_3(), "rule__Assembly__Group_14_3__0");
					put(grammarAccess.getAssemblyAccess().getGroup_15(), "rule__Assembly__Group_15__0");
					put(grammarAccess.getAssemblyAccess().getGroup_15_3(), "rule__Assembly__Group_15_3__0");
					put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
					put(grammarAccess.getCompInstanceAccess().getGroup(), "rule__CompInstance__Group__0");
					put(grammarAccess.getCompInstanceAccess().getGroup_2(), "rule__CompInstance__Group_2__0");
					put(grammarAccess.getCompInstanceAccess().getGroup_7(), "rule__CompInstance__Group_7__0");
					put(grammarAccess.getCompInstanceAccess().getGroup_7_2(), "rule__CompInstance__Group_7_2__0");
					put(grammarAccess.getInstConnectionAccess().getGroup(), "rule__InstConnection__Group__0");
					put(grammarAccess.getConstraint_expressionAccess().getGroup_0(), "rule__Constraint_expression__Group_0__0");
					put(grammarAccess.getConstraint_expressionAccess().getGroup_1(), "rule__Constraint_expression__Group_1__0");
					put(grammarAccess.getLogical_constraintAccess().getGroup_0(), "rule__Logical_constraint__Group_0__0");
					put(grammarAccess.getLogical_constraintAccess().getGroup_1(), "rule__Logical_constraint__Group_1__0");
					put(grammarAccess.getRelational_constraintAccess().getGroup(), "rule__Relational_constraint__Group__0");
					put(grammarAccess.getInstance_attributeAccess().getGroup(), "rule__Instance_attribute__Group__0");
					put(grammarAccess.getAttribute_valueAccess().getGroup(), "rule__Attribute_value__Group__0");
					put(grammarAccess.getVersionAccess().getGroup(), "rule__Version__Group__0");
					put(grammarAccess.getPre_versionAccess().getGroup(), "rule__Pre_version__Group__0");
					put(grammarAccess.getChangeAccess().getGroup(), "rule__Change__Group__0");
					put(grammarAccess.getChangeAccess().getGroup_16(), "rule__Change__Group_16__0");
					put(grammarAccess.getDedalDiagramAccess().getNameAssignment_1(), "rule__DedalDiagram__NameAssignment_1");
					put(grammarAccess.getDedalDiagramAccess().getArchitectureDescriptionsAssignment_2_0_2(), "rule__DedalDiagram__ArchitectureDescriptionsAssignment_2_0_2");
					put(grammarAccess.getDedalDiagramAccess().getArchitectureDescriptionsAssignment_2_0_3_1(), "rule__DedalDiagram__ArchitectureDescriptionsAssignment_2_0_3_1");
					put(grammarAccess.getDedalDiagramAccess().getRepositoriesAssignment_2_1_2(), "rule__DedalDiagram__RepositoriesAssignment_2_1_2");
					put(grammarAccess.getDedalDiagramAccess().getRepositoriesAssignment_2_1_3_1(), "rule__DedalDiagram__RepositoriesAssignment_2_1_3_1");
					put(grammarAccess.getRepositoryAccess().getNameAssignment_1(), "rule__Repository__NameAssignment_1");
					put(grammarAccess.getRepositoryAccess().getComponentsAssignment_2_2(), "rule__Repository__ComponentsAssignment_2_2");
					put(grammarAccess.getRepositoryAccess().getComponentsAssignment_2_3_1(), "rule__Repository__ComponentsAssignment_2_3_1");
					put(grammarAccess.getRepositoryAccess().getInterfaceTypesAssignment_3_2(), "rule__Repository__InterfaceTypesAssignment_3_2");
					put(grammarAccess.getRepositoryAccess().getInterfaceTypesAssignment_3_3_1(), "rule__Repository__InterfaceTypesAssignment_3_3_1");
					put(grammarAccess.getInterfaceTypeAccess().getNameAssignment_1(), "rule__InterfaceType__NameAssignment_1");
					put(grammarAccess.getInterfaceTypeAccess().getSignaturesAssignment_4(), "rule__InterfaceType__SignaturesAssignment_4");
					put(grammarAccess.getInterfaceTypeAccess().getSignaturesAssignment_5_1(), "rule__InterfaceType__SignaturesAssignment_5_1");
					put(grammarAccess.getSignatureAccess().getIdAssignment_1(), "rule__Signature__IdAssignment_1");
					put(grammarAccess.getSignatureAccess().getNameAssignment_2_1(), "rule__Signature__NameAssignment_2_1");
					put(grammarAccess.getSignatureAccess().getTypeAssignment_3_1(), "rule__Signature__TypeAssignment_3_1");
					put(grammarAccess.getSignatureAccess().getParametersAssignment_4_2(), "rule__Signature__ParametersAssignment_4_2");
					put(grammarAccess.getSignatureAccess().getParametersAssignment_4_3_1(), "rule__Signature__ParametersAssignment_4_3_1");
					put(grammarAccess.getParameterAccess().getIdAssignment_1(), "rule__Parameter__IdAssignment_1");
					put(grammarAccess.getParameterAccess().getNameAssignment_2_1(), "rule__Parameter__NameAssignment_2_1");
					put(grammarAccess.getParameterAccess().getTypeAssignment_3_1(), "rule__Parameter__TypeAssignment_3_1");
					put(grammarAccess.getSpecificationAccess().getNameAssignment_1(), "rule__Specification__NameAssignment_1");
					put(grammarAccess.getSpecificationAccess().getSpecComponentsAssignment_2_1(), "rule__Specification__SpecComponentsAssignment_2_1");
					put(grammarAccess.getSpecificationAccess().getSpecComponentsAssignment_2_2_1(), "rule__Specification__SpecComponentsAssignment_2_2_1");
					put(grammarAccess.getSpecificationAccess().getSpecConnectionsAssignment_3_1(), "rule__Specification__SpecConnectionsAssignment_3_1");
					put(grammarAccess.getSpecificationAccess().getSpecConnectionsAssignment_3_2(), "rule__Specification__SpecConnectionsAssignment_3_2");
					put(grammarAccess.getSpecificationAccess().getInterfaceTypesAssignment_7_1(), "rule__Specification__InterfaceTypesAssignment_7_1");
					put(grammarAccess.getSpecificationAccess().getInterfaceTypesAssignment_7_2_1(), "rule__Specification__InterfaceTypesAssignment_7_2_1");
					put(grammarAccess.getCompRoleAccess().getNameAssignment_1(), "rule__CompRole__NameAssignment_1");
					put(grammarAccess.getCompRoleAccess().getIdAssignment_3(), "rule__CompRole__IdAssignment_3");
					put(grammarAccess.getCompRoleAccess().getCompInterfacesAssignment_4_1(), "rule__CompRole__CompInterfacesAssignment_4_1");
					put(grammarAccess.getCompRoleAccess().getCompInterfacesAssignment_4_2_1(), "rule__CompRole__CompInterfacesAssignment_4_2_1");
					put(grammarAccess.getCompRoleAccess().getCompInterfacesAssignment_5_1(), "rule__CompRole__CompInterfacesAssignment_5_1");
					put(grammarAccess.getCompRoleAccess().getCompInterfacesAssignment_5_2_1(), "rule__CompRole__CompInterfacesAssignment_5_2_1");
					put(grammarAccess.getCompRoleAccess().getMinInstanceNbrAssignment_6_1(), "rule__CompRole__MinInstanceNbrAssignment_6_1");
					put(grammarAccess.getCompRoleAccess().getMaxInstanceNbrAssignment_7_1(), "rule__CompRole__MaxInstanceNbrAssignment_7_1");
					put(grammarAccess.getCompRoleAccess().getCompInterfacesAssignment_8_1(), "rule__CompRole__CompInterfacesAssignment_8_1");
					put(grammarAccess.getCompRoleAccess().getCompInterfacesAssignment_8_2_1(), "rule__CompRole__CompInterfacesAssignment_8_2_1");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_1(), "rule__Interface__NameAssignment_1");
					put(grammarAccess.getInterfaceAccess().getDirectionAssignment_3(), "rule__Interface__DirectionAssignment_3");
					put(grammarAccess.getInterfaceAccess().getTypeAssignment_5(), "rule__Interface__TypeAssignment_5");
					put(grammarAccess.getInterfaceAccess().getDelegationAssignment_6_1(), "rule__Interface__DelegationAssignment_6_1");
					put(grammarAccess.getInterfaceAccess().getInstantiatesAssignment_7_1(), "rule__Interface__InstantiatesAssignment_7_1");
					put(grammarAccess.getRoleConnectionAccess().getRefIDAssignment_1(), "rule__RoleConnection__RefIDAssignment_1");
					put(grammarAccess.getRoleConnectionAccess().getClientCompElemAssignment_3(), "rule__RoleConnection__ClientCompElemAssignment_3");
					put(grammarAccess.getRoleConnectionAccess().getClientIntElemAssignment_5(), "rule__RoleConnection__ClientIntElemAssignment_5");
					put(grammarAccess.getRoleConnectionAccess().getServerCompElemAssignment_7(), "rule__RoleConnection__ServerCompElemAssignment_7");
					put(grammarAccess.getRoleConnectionAccess().getServerIntElemAssignment_9(), "rule__RoleConnection__ServerIntElemAssignment_9");
					put(grammarAccess.getConfigurationAccess().getNameAssignment_1(), "rule__Configuration__NameAssignment_1");
					put(grammarAccess.getConfigurationAccess().getImplementsAssignment_2_1(), "rule__Configuration__ImplementsAssignment_2_1");
					put(grammarAccess.getConfigurationAccess().getImplementsAssignment_2_3_1(), "rule__Configuration__ImplementsAssignment_2_3_1");
					put(grammarAccess.getConfigurationAccess().getConfigComponentsAssignment_6_1(), "rule__Configuration__ConfigComponentsAssignment_6_1");
					put(grammarAccess.getConfigurationAccess().getConfigComponentsAssignment_6_2_1(), "rule__Configuration__ConfigComponentsAssignment_6_2_1");
					put(grammarAccess.getConfigurationAccess().getInterfaceTypesAssignment_8_2(), "rule__Configuration__InterfaceTypesAssignment_8_2");
					put(grammarAccess.getConfigurationAccess().getInterfaceTypesAssignment_8_3_1(), "rule__Configuration__InterfaceTypesAssignment_8_3_1");
					put(grammarAccess.getConfigurationAccess().getComptypesAssignment_9_2(), "rule__Configuration__ComptypesAssignment_9_2");
					put(grammarAccess.getConfigurationAccess().getComptypesAssignment_9_3_1(), "rule__Configuration__ComptypesAssignment_9_3_1");
					put(grammarAccess.getConfigurationAccess().getConfigConnectionsAssignment_10_2(), "rule__Configuration__ConfigConnectionsAssignment_10_2");
					put(grammarAccess.getConfigurationAccess().getConfigConnectionsAssignment_10_3_1(), "rule__Configuration__ConfigConnectionsAssignment_10_3_1");
					put(grammarAccess.getCompTypeAccess().getNameAssignment_1(), "rule__CompType__NameAssignment_1");
					put(grammarAccess.getCompTypeAccess().getIdAssignment_3(), "rule__CompType__IdAssignment_3");
					put(grammarAccess.getCompTypeAccess().getCompInterfacesAssignment_4_1(), "rule__CompType__CompInterfacesAssignment_4_1");
					put(grammarAccess.getCompTypeAccess().getCompInterfacesAssignment_4_2_1(), "rule__CompType__CompInterfacesAssignment_4_2_1");
					put(grammarAccess.getCompTypeAccess().getCompInterfacesAssignment_5_1(), "rule__CompType__CompInterfacesAssignment_5_1");
					put(grammarAccess.getCompTypeAccess().getCompInterfacesAssignment_5_2_1(), "rule__CompType__CompInterfacesAssignment_5_2_1");
					put(grammarAccess.getCompTypeAccess().getCompInterfacesAssignment_6_1(), "rule__CompType__CompInterfacesAssignment_6_1");
					put(grammarAccess.getCompTypeAccess().getCompInterfacesAssignment_6_2_1(), "rule__CompType__CompInterfacesAssignment_6_2_1");
					put(grammarAccess.getCompClass_ImplAccess().getNameAssignment_1(), "rule__CompClass_Impl__NameAssignment_1");
					put(grammarAccess.getCompClass_ImplAccess().getRealizesAssignment_2_1(), "rule__CompClass_Impl__RealizesAssignment_2_1");
					put(grammarAccess.getCompClass_ImplAccess().getRealizesAssignment_2_2_1(), "rule__CompClass_Impl__RealizesAssignment_2_2_1");
					put(grammarAccess.getCompClass_ImplAccess().getIdAssignment_4(), "rule__CompClass_Impl__IdAssignment_4");
					put(grammarAccess.getCompClass_ImplAccess().getImplementsAssignment_6(), "rule__CompClass_Impl__ImplementsAssignment_6");
					put(grammarAccess.getCompClass_ImplAccess().getContentAssignment_7_1(), "rule__CompClass_Impl__ContentAssignment_7_1");
					put(grammarAccess.getCompClass_ImplAccess().getAttributesAssignment_8_2(), "rule__CompClass_Impl__AttributesAssignment_8_2");
					put(grammarAccess.getCompClass_ImplAccess().getAttributesAssignment_8_3_1(), "rule__CompClass_Impl__AttributesAssignment_8_3_1");
					put(grammarAccess.getCompClass_ImplAccess().getCompInterfacesAssignment_11_1(), "rule__CompClass_Impl__CompInterfacesAssignment_11_1");
					put(grammarAccess.getCompClass_ImplAccess().getCompInterfacesAssignment_11_2_1(), "rule__CompClass_Impl__CompInterfacesAssignment_11_2_1");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_0(), "rule__Attribute__TypeAssignment_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getCompositeCompClassAccess().getNameAssignment_1(), "rule__CompositeCompClass__NameAssignment_1");
					put(grammarAccess.getCompositeCompClassAccess().getIdAssignment_3(), "rule__CompositeCompClass__IdAssignment_3");
					put(grammarAccess.getCompositeCompClassAccess().getImplementsAssignment_5(), "rule__CompositeCompClass__ImplementsAssignment_5");
					put(grammarAccess.getCompositeCompClassAccess().getUsesAssignment_6_1(), "rule__CompositeCompClass__UsesAssignment_6_1");
					put(grammarAccess.getCompositeCompClassAccess().getAttributesAssignment_8_2(), "rule__CompositeCompClass__AttributesAssignment_8_2");
					put(grammarAccess.getCompositeCompClassAccess().getAttributesAssignment_8_3_1(), "rule__CompositeCompClass__AttributesAssignment_8_3_1");
					put(grammarAccess.getCompositeCompClassAccess().getRealizesAssignment_11_2(), "rule__CompositeCompClass__RealizesAssignment_11_2");
					put(grammarAccess.getCompositeCompClassAccess().getRealizesAssignment_11_3_1(), "rule__CompositeCompClass__RealizesAssignment_11_3_1");
					put(grammarAccess.getCompositeCompClassAccess().getCompInterfacesAssignment_12_1(), "rule__CompositeCompClass__CompInterfacesAssignment_12_1");
					put(grammarAccess.getCompositeCompClassAccess().getCompInterfacesAssignment_12_2_1(), "rule__CompositeCompClass__CompInterfacesAssignment_12_2_1");
					put(grammarAccess.getCompositeCompClassAccess().getDelegatedInterfacesAssignment_13_1(), "rule__CompositeCompClass__DelegatedInterfacesAssignment_13_1");
					put(grammarAccess.getCompositeCompClassAccess().getDelegatedInterfacesAssignment_13_2_1(), "rule__CompositeCompClass__DelegatedInterfacesAssignment_13_2_1");
					put(grammarAccess.getClassConnectionAccess().getRefIDAssignment_1(), "rule__ClassConnection__RefIDAssignment_1");
					put(grammarAccess.getClassConnectionAccess().getPropertyAssignment_3(), "rule__ClassConnection__PropertyAssignment_3");
					put(grammarAccess.getClassConnectionAccess().getClientClassElemAssignment_5(), "rule__ClassConnection__ClientClassElemAssignment_5");
					put(grammarAccess.getClassConnectionAccess().getClientIntElemAssignment_7(), "rule__ClassConnection__ClientIntElemAssignment_7");
					put(grammarAccess.getClassConnectionAccess().getServerClassElemAssignment_9(), "rule__ClassConnection__ServerClassElemAssignment_9");
					put(grammarAccess.getClassConnectionAccess().getServerIntElemAssignment_11(), "rule__ClassConnection__ServerIntElemAssignment_11");
					put(grammarAccess.getPort_ImplAccess().getNameAssignment_1(), "rule__Port_Impl__NameAssignment_1");
					put(grammarAccess.getPort_ImplAccess().getInterfacesAssignment_4(), "rule__Port_Impl__InterfacesAssignment_4");
					put(grammarAccess.getPort_ImplAccess().getInterfacesAssignment_5_1(), "rule__Port_Impl__InterfacesAssignment_5_1");
					put(grammarAccess.getCompositePortAccess().getNameAssignment_1(), "rule__CompositePort__NameAssignment_1");
					put(grammarAccess.getCompositePortAccess().getPortsAssignment_4(), "rule__CompositePort__PortsAssignment_4");
					put(grammarAccess.getCompositePortAccess().getPortsAssignment_5_1(), "rule__CompositePort__PortsAssignment_5_1");
					put(grammarAccess.getAssemblyAccess().getNameAssignment_1(), "rule__Assembly__NameAssignment_1");
					put(grammarAccess.getAssemblyAccess().getInstantiatesAssignment_3(), "rule__Assembly__InstantiatesAssignment_3");
					put(grammarAccess.getAssemblyAccess().getAssmComponentsAssignment_8(), "rule__Assembly__AssmComponentsAssignment_8");
					put(grammarAccess.getAssemblyAccess().getAssmComponentsAssignment_9_1(), "rule__Assembly__AssmComponentsAssignment_9_1");
					put(grammarAccess.getAssemblyAccess().getInterfaceTypesAssignment_14_2(), "rule__Assembly__InterfaceTypesAssignment_14_2");
					put(grammarAccess.getAssemblyAccess().getInterfaceTypesAssignment_14_3_1(), "rule__Assembly__InterfaceTypesAssignment_14_3_1");
					put(grammarAccess.getAssemblyAccess().getAssemblyConnectionsAssignment_15_2(), "rule__Assembly__AssemblyConnectionsAssignment_15_2");
					put(grammarAccess.getAssemblyAccess().getAssemblyConnectionsAssignment_15_3_1(), "rule__Assembly__AssemblyConnectionsAssignment_15_3_1");
					put(grammarAccess.getCompInstanceAccess().getNameAssignment_1(), "rule__CompInstance__NameAssignment_1");
					put(grammarAccess.getCompInstanceAccess().getRoleAssignment_2_1(), "rule__CompInstance__RoleAssignment_2_1");
					put(grammarAccess.getCompInstanceAccess().getIdAssignment_4(), "rule__CompInstance__IdAssignment_4");
					put(grammarAccess.getCompInstanceAccess().getInstantiatesAssignment_6(), "rule__CompInstance__InstantiatesAssignment_6");
					put(grammarAccess.getCompInstanceAccess().getCompInterfacesAssignment_7_1(), "rule__CompInstance__CompInterfacesAssignment_7_1");
					put(grammarAccess.getCompInstanceAccess().getCompInterfacesAssignment_7_2_1(), "rule__CompInstance__CompInterfacesAssignment_7_2_1");
					put(grammarAccess.getInstConnectionAccess().getRefIDAssignment_1(), "rule__InstConnection__RefIDAssignment_1");
					put(grammarAccess.getInstConnectionAccess().getClientInstElemAssignment_3(), "rule__InstConnection__ClientInstElemAssignment_3");
					put(grammarAccess.getInstConnectionAccess().getClientIntElemAssignment_5(), "rule__InstConnection__ClientIntElemAssignment_5");
					put(grammarAccess.getInstConnectionAccess().getServerInstElemAssignment_7(), "rule__InstConnection__ServerInstElemAssignment_7");
					put(grammarAccess.getInstConnectionAccess().getServerIntElemAssignment_9(), "rule__InstConnection__ServerIntElemAssignment_9");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.ema.dedal.xtext.ui.contentassist.antlr.internal.InternalDedalADLParser typedParser = (fr.ema.dedal.xtext.ui.contentassist.antlr.internal.InternalDedalADLParser) parser;
			typedParser.entryRuleDedalDiagram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DedalADLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DedalADLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
