/*
 * generated by Xtext
 */
package fr.ema.dedal.xtext.ui.contentassist

import fr.ema.dedal.xtext.ui.contentassist.AbstractDedalADLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DedalADLProposalProvider extends AbstractDedalADLProposalProvider {
}
