/**
 * generated by Xtext
 */
package fr.ema.dedal.xtext.serializer;

import fr.ema.dedal.xtext.serializer.AbstractDedalADLSyntacticSequencer;

@SuppressWarnings("all")
public class DedalADLSyntacticSequencer extends AbstractDedalADLSyntacticSequencer {
}
