/**
 * generated by Xtext
 */
package fr.ema.dedal.xtext.serializer;

import fr.ema.dedal.xtext.serializer.AbstractDedalADLSemanticSequencer;

@SuppressWarnings("all")
public class DedalADLSemanticSequencer extends AbstractDedalADLSemanticSequencer {
}
